### PR TITLE
Added podspec for version 0.0.1

### PR DESCRIPTION
**Pull request by ulian-onua**
This pull request adds support of CocoaPods for your class.
Please merge this pull request and then add tag "0.0.1" to your master branch.
After that, we can be able to add your class to public CocoaPods repository and therefore to CocoaPods.

### CODE REVIEW

**Comment by timonus** [comment]
Thanks! Will push to Cocoapods in a bit.

**Comment by ulian-onua** [comment]
@timonus you are welcome.
To push to Cocoapods you have to use the following command from a terminal:
"pod trunk push TJActivityViewController.podspec"

You have to install Cocoapods on your working machine before that:
https://cocoapods.org/

**Comment by timonus** [comment]
Pushed it this morning :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ulian-onua** [comment]
Great! Thank you!

**Pull request merged**
